version: '3'
services:
  web:
    build: .
    ports:
    - "3000:3000"
    links:
     - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    ports:
      - "9200:9200"
